from gkgaas.triplegeo.classification import Category, \
    ClassificationSpecification

osm_poi_3_0_classification = ClassificationSpecification(
    file_name='OSM_POI_3.0_classification.yml',
    categories=[
        Category(
            name='ACCOMMODATION',
            category_id='A',
            sub_classes=[
                ('ALPINEHUT', '1'),
                ('CAMPING', '2'),
                ('CARAVAN', '3'),
                ('CHALET', '4'),
                ('GUESTHOUSE', '5'),
                ('HOSTEL', '6'),
                ('HOTEL', '7'),
                ('MOTEL', '8')]),
        Category(
            name='BUSINESS',
            category_id='B',
            sub_classes=[
                ('ADVERTISING', '9'),
                ('ATM', '10'),
                ('AUDIOVISUAL', '11'),
                ('BANK', '12'),
                ('CONSTRUCTION', '13'),
                ('CURRENCY', '14'),
                ('EMPLOYMENT', '15'),
                ('ENERGY', '16'),
                ('FINANCIAL', '17'),
                ('INSURANCE', '18'),
                ('IT', '19'),
                ('LEGAL', '20'),
                ('PRESS', '21'),
                ('REALESTATE', '22'),
                ('TELECOM', '23'),
                ('TRAVELAGENCY', '24')]),
        Category(
            name='AUTOMOTIVE',
            category_id='C',
            sub_classes=[
                ('CARWASH', '25'),
                ('CHARGINGSTATION', '26'),
                ('FUEL', '27'),
                ('PARKING', '28'),
                ('RENTALCAR', '29'),
                ('RESTAREA', '30'),
                ('TOLLGATE', '31')]),
        Category(
            name='EAT/DRINK',
            category_id='D',
            sub_classes=[
                ('BAR', '32'),
                ('BIERGARTEN', '33'),
                ('CAFE', '34'),
                ('FASTFOOD', '35'),
                ('ICECREAM', '36'),
                ('INTERNETCAFE', '37'),
                ('PUB', '38'),
                ('RESTAURANT', '39')]),
        Category(
            name='EDUCATION',
            category_id='E',
            sub_classes=[
                ('COLLEGE', '40'),
                ('NURSERY', '41'),
                ('SCHOOL', '42'),
                ('UNIVERSITY', '43')]),
        Category(
            name='SPORT',
            category_id='F',
            sub_classes=[
                ('ARCHERY', '44'),
                ('BASEBALL', '45'),
                ('BASKETBALL', '46'),
                ('BOWLING', '47'),
                ('CANOE', '48'),
                ('CLIMBING', '49'),
                ('CRICKET', '50'),
                ('DIVING', '51'),
                ('FOOTBALL', '52'),
                ('GOLF', '53'),
                ('GYM', '54'),
                ('HANDBALL', '55'),
                ('HOCKEY', '56'),
                ('HORSE', '57'),
                ('ICESKATING', '58'),
                ('LEISURECENTER', '59'),
                ('MARINA', '60'),
                ('MOTORRACING', '61'),
                ('PLAYGROUND', '62'),
                ('RUGBY', '63'),
                ('SHOOTING', '64'),
                ('SKATING', '65'),
                ('SKIING', '66'),
                ('SNOOKER', '67'),
                ('SOCCER', '68'),
                ('STADIUM', '69'),
                ('SURFING', '70'),
                ('SWIMMING', '71'),
                ('TENNIS', '72'),
                ('VOLLEYBALL', '73'),
                ('WATERSKI', '74')]),
        Category(
            name='PUBLICSERVICE',
            category_id='G',
            sub_classes=[
                ('ASSOCIATION', '75'),
                ('COURT', '76'),
                ('EDUCATIONAL', '77'),
                ('EMBASSY', '78'),
                ('FIRESTATION', '79'),
                ('FOUNDATION', '80'),
                ('GOVERNMENT', '81'),
                ('LIBRARY', '82'),
                ('NGO', '83'),
                ('POLICE', '84'),
                ('POSTOFFICE', '85'),
                ('PRISON', '86'),
                ('PUBLICBUILDING', '87'),
                ('SOCIALCARE', '88'),
                ('TOILETS', '89'),
                ('TOWNHALL', '90')]),
        Category(
            name='HEALTH',
            category_id='H',
            sub_classes=[
                ('CLINIC', '91'),
                ('DENTIST', '92'),
                ('DOCTORS', '93'),
                ('EMERGENCYSTATION', '94'),
                ('HOSPITAL', '95'),
                ('PHARMACY', '96'),
                ('VETERINARY', '97')]),
        Category(
            name='RELIGIOUS',
            category_id='I',
            sub_classes=[
                ('BAHAI', '98'),
                ('BUDDHIST', '99'),
                ('CHRISTIAN', '100'),
                ('HINDU', '101'),
                ('ISLAMIC', '102'),
                ('JAIN', '103'),
                ('JEWISH', '104'),
                ('PAGAN', '105'),
                ('SHINTO', '106'),
                ('SIKH', '107'),
                ('TAOIST', '108'),
                ('UNKNOWN', '109'),
                ('ZOROASTRIAN', '110')]),
        Category(
            name='SETTLEMENTS',
            category_id='J',
            sub_classes=[
                ('CITY', '111'),
                ('HAMLET', '112'),
                ('SUBURB', '113'),
                ('TOWN', '114'),
                ('VILLAGE', '115')]),
        Category(
            name='SHOP',
            category_id='K',
            sub_classes=[
                ('ALCOHOL', '116'),
                ('APPLIANCE', '117'),
                ('ART', '118'),
                ('BABYGOODS', '119'),
                ('BAKERY', '120'),
                ('BICYCLE', '121'),
                ('BOOK', '122'),
                ('BUTCHER', '123'),
                ('CAR', '124'),
                ('CARREPAIR', '125'),
                ('CLOTHES', '126'),
                ('COMPUTER', '127'),
                ('CONFECTIONERY', '128'),
                ('CONVENIENCE', '129'),
                ('COPYSHOP', '130'),
                ('COSMETICS', '131'),
                ('DEPARTMENTSTORE', '132'),
                ('DIY', '133'),
                ('ELECTRONICS', '134'),
                ('FISH', '135'),
                ('FLORIST', '136'),
                ('FURNITURE', '137'),
                ('GAMPLING', '138'),
                ('GARDENCENTRE', '139'),
                ('GIFT', '140'),
                ('GREENGROCER', '141'),
                ('GUN', '142'),
                ('HAIRDRESSER', '143'),
                ('HEARINGAIDS', '144'),
                ('JEWELRY', '145'),
                ('KIOSK', '146'),
                ('KITCHEN', '147'),
                ('LAUNDRETTE', '148'),
                ('MARKETPLACE', '149'),
                ('MASSAGE', '150'),
                ('MOTORCYCLE', '151'),
                ('MUSIC', '152'),
                ('NEWSPAPER', '153'),
                ('OPTICIAN', '154'),
                ('PAWNBROKER', '155'),
                ('PET', '156'),
                ('PHONE', '157'),
                ('PHOTO', '158'),
                ('RETAIL', '159'),
                ('SHOES', '160'),
                ('SPORTS', '161'),
                ('SUPERMARKET', '162'),
                ('TAILOR', '163'),
                ('TATTOO', '164'),
                ('TOBACCO', '165'),
                ('TOYS', '166'),
                ('VIDEORENTAL', '167'),
                ('WATCHES', '168')]),
        Category(
            name='LANDUSE',
            category_id='L',
            sub_classes=[
                ('CEMETERY', '169'),
                ('CONIFEROUSFOREST', '170'),
                ('DAM', '171'),
                ('DECIDUOUSFOREST', '172'),
                ('DUMP', '173'),
                ('FARM', '174'),
                ('FOREST', '175'),
                ('GRASS', '176'),
                ('INDUSTRIAL', '177'),
                ('MILITARY', '178'),
                ('MINESHAFT', '179'),
                ('NATURERESERVE', '180'),
                ('PARK', '181'),
                ('QUARRY', '182'),
                ('RIVERBANK', '183'),
                ('ROCK', '184'),
                ('SCRUB', '185'),
                ('SWAMP', '186'),
                ('WATER', '187')]),
        Category(
            name='TOURISM',
            category_id='M',
            sub_classes=[
                ('ARCHAELOGICAL', '188'),
                ('ART', '189'),
                ('ATTRACTION', '190'),
                ('BATTLEFIELD', '191'),
                ('BEACH', '192'),
                ('BUNKER', '193'),
                ('CASINO', '194'),
                ('CASTLE', '195'),
                ('CAVE', '196'),
                ('CINEMA', '197'),
                ('CLOCK', '198'),
                ('EVENTVENUE', '199'),
                ('FOUNTAIN', '200'),
                ('GATE', '201'),
                ('GLACIER', '202'),
                ('INFORMATION', '203'),
                ('LIGHTHOUSE', '204'),
                ('MEMORIAL', '205'),
                ('MONUMENT', '206'),
                ('MUSEUM', '207'),
                ('NIGHTCLUB', '208'),
                ('PEAK', '209'),
                ('PEDESTRIAN', '210'),
                ('RUINS', '211'),
                ('SHELTER', '212'),
                ('THEATRE', '213'),
                ('THEMEPARK', '214'),
                ('TOWER', '215'),
                ('TOWERCOMMUNICATION', '216'),
                ('VOLCANO', '217'),
                ('WATERMILL', '218'),
                ('WATERTOWER', '219'),
                ('WINDMILL', '220'),
                ('WRECK', '221'),
                ('ZOO', '222')]),
        Category(
            name='TRANSPORT',
            category_id='N',
            sub_classes=[
                ('AIRPORT', '223'),
                ('AIRTERMINAL', '224'),
                ('BUSSTOP', '225'),
                ('FERRYTERMINAL', '226'),
                ('STATION', '227'),
                ('SUBWAY', '228'),
                ('TRAMSTOP', '229')])])
