from rdflib import URIRef

from gkgaas.fagi import SerializationFormat, LinksFormat, FusionMode
from gkgaas.fagi.action import DatasetAction, FusionAction, ValidationAction
from gkgaas.fagi.condition import FAGIRuleCondition, \
    SimpleFAGIRuleConditionExpression, And
from gkgaas.fagi.config import FAGIConfig
from gkgaas.fagi.fagiprofile import FAGIProfile
from gkgaas.fagi.filesettings import LeftInputDatasetSettings, \
    RightInputDatasetSettings, LinksFileSettings, FusedOutputDatasetSettings
from gkgaas.fagi.function import Exists, IsSameCustomNormalize, \
    GeometriesCloserThan, IsSamePhoneNumberCustomNormalize
from gkgaas.fagi.rule import FAGIRulesSpec, Ensembles, FAGIRule, ActionRule, \
    FAGIValidationRule, ExternalProperty, ValidationActionRule

slipo_default_aa_mode = FAGIProfile(
    config=FAGIConfig(
        input_format=SerializationFormat.NT,
        output_format=SerializationFormat.NT,
        left=LeftInputDatasetSettings(id='a'),
        right=RightInputDatasetSettings(id='b'),
        links=LinksFileSettings(
            id='links',
            links_format=LinksFormat.CSV_UNIQUE_LINKS
        ),
        target=FusedOutputDatasetSettings(
            id='target',
            mode=FusionMode.AA,
            fused='fused.nt',
            remaining='remaining.nt',
            ambiguous='review.nt',
            statistics='stats.json'
        ),
    ),
    rules=FAGIRulesSpec(
        rules=[
            FAGIValidationRule(
                default_action=ValidationAction.ACCEPT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                property_b=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                default_action=FusionAction.KEEP_MORE_POINTS,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#locality'),
                property_b=URIRef('http://slipo.eu/def#locality'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#country'),
                property_b=URIRef('http://slipo.eu/def#country'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#homepage'),
                property_b=URIRef('http://slipo.eu/def#homepage'),
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            )
        ],
        default_dataset_action=DatasetAction.KEEP_LEFT,
        ensembles=Ensembles(
            functional_properties=[],
            non_functional_properties=[]
        )
    )
)

slipo_default_ab_mode = FAGIProfile(
    config=FAGIConfig(
        input_format=SerializationFormat.NT,
        output_format=SerializationFormat.NT,
        left=LeftInputDatasetSettings(id='a'),
        right=RightInputDatasetSettings(id='b'),
        links=LinksFileSettings(
            id='links',
            links_format=LinksFormat.CSV_UNIQUE_LINKS
        ),
        target=FusedOutputDatasetSettings(
            id='target',
            mode=FusionMode.AB,
            fused='fused.nt',
            remaining='remaining.nt',
            ambiguous='review.nt',
            statistics='stats.json'
        )
    ),
    rules=FAGIRulesSpec(
        rules=[
            FAGIValidationRule(
                default_action=ValidationAction.ACCEPT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                property_b=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                default_action=FusionAction.KEEP_MORE_POINTS,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#locality'),
                property_b=URIRef('http://slipo.eu/def#locality'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#country'),
                property_b=URIRef('http://slipo.eu/def#country'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#homepage'),
                property_b=URIRef('http://slipo.eu/def#homepage'),
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            )
        ],
        default_dataset_action=DatasetAction.KEEP_LEFT,
        ensembles=Ensembles(
            functional_properties=[],
            non_functional_properties=[]
        )
    )
)

slipo_default_a_mode = FAGIProfile(
    config=FAGIConfig(
        input_format=SerializationFormat.NT,
        output_format=SerializationFormat.NT,
        left=LeftInputDatasetSettings(id='a'),
        right=RightInputDatasetSettings(id='b'),
        links=LinksFileSettings(
            id='links',
            links_format=LinksFormat.CSV_UNIQUE_LINKS
        ),
        target=FusedOutputDatasetSettings(
            id='target',
            mode=FusionMode.A,
            fused='fused.nt',
            remaining='remaining.nt',
            ambiguous='review.nt',
            statistics='stats.json'
        )
    ),
    rules=FAGIRulesSpec(
        rules=[
            FAGIValidationRule(
                default_action=ValidationAction.ACCEPT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                property_b=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                default_action=FusionAction.KEEP_MORE_POINTS,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#locality'),
                property_b=URIRef('http://slipo.eu/def#locality'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#country'),
                property_b=URIRef('http://slipo.eu/def#country'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#homepage'),
                property_b=URIRef('http://slipo.eu/def#homepage'),
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            )
        ],
        default_dataset_action=DatasetAction.KEEP_LEFT,
        ensembles=Ensembles(
            functional_properties=[],
            non_functional_properties=[]
        )
    )
)

slipo_default_ba_mode = FAGIProfile(
    config=FAGIConfig(
        input_format=SerializationFormat.NT,
        output_format=SerializationFormat.NT,
        left=LeftInputDatasetSettings(id='a'),
        right=RightInputDatasetSettings(id='b'),
        links=LinksFileSettings(
            id='links',
            links_format=LinksFormat.CSV_UNIQUE_LINKS
        ),
        target=FusedOutputDatasetSettings(
            id='target',
            mode=FusionMode.BA,
            fused='fused.nt',
            remaining='remaining.nt',
            ambiguous='review.nt',
            statistics='stats.json'
        )
    ),
    rules=FAGIRulesSpec(
        rules=[
            FAGIValidationRule(
                default_action=ValidationAction.ACCEPT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                property_b=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                default_action=FusionAction.KEEP_MORE_POINTS,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#locality'),
                property_b=URIRef('http://slipo.eu/def#locality'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#country'),
                property_b=URIRef('http://slipo.eu/def#country'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#homepage'),
                property_b=URIRef('http://slipo.eu/def#homepage'),
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_RIGHT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            )
        ],
        default_dataset_action=DatasetAction.KEEP_LEFT,
        ensembles=Ensembles(
            functional_properties=[],
            non_functional_properties=[]
        )
    )
)

slipo_default_bb_mode = FAGIProfile(
    config=FAGIConfig(
        input_format=SerializationFormat.NT,
        output_format=SerializationFormat.NT,
        left=LeftInputDatasetSettings(id='a'),
        right=RightInputDatasetSettings(id='b'),
        links=LinksFileSettings(
            id='links',
            links_format=LinksFormat.CSV_UNIQUE_LINKS
        ),
        target=FusedOutputDatasetSettings(
            id='target',
            mode=FusionMode.BB,
            fused='fused.nt',
            remaining='remaining.nt',
            ambiguous='review.nt',
            statistics='stats.json'
        )
    ),
    rules=FAGIRulesSpec(
        rules=[
            FAGIValidationRule(
                default_action=ValidationAction.ACCEPT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                property_b=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                default_action=FusionAction.KEEP_MORE_POINTS,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#locality'),
                property_b=URIRef('http://slipo.eu/def#locality'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#country'),
                property_b=URIRef('http://slipo.eu/def#country'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#homepage'),
                property_b=URIRef('http://slipo.eu/def#homepage'),
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            )
        ],
        default_dataset_action=DatasetAction.KEEP_LEFT,
        ensembles=Ensembles(
            functional_properties=[],
            non_functional_properties=[]
        )
    )
)

slipo_default_b_mode = FAGIProfile(
    config=FAGIConfig(
        input_format=SerializationFormat.NT,
        output_format=SerializationFormat.NT,
        left=LeftInputDatasetSettings(id='a'),
        right=RightInputDatasetSettings(id='b'),
        links=LinksFileSettings(
            id='links',
            links_format=LinksFormat.CSV_UNIQUE_LINKS
        ),
        target=FusedOutputDatasetSettings(
            id='target',
            mode=FusionMode.B,
            fused='fused.nt',
            remaining='remaining.nt',
            ambiguous='review.nt',
            statistics='stats.json'
        )
    ),
    rules=FAGIRulesSpec(
        rules=[
            FAGIValidationRule(
                default_action=ValidationAction.ACCEPT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                property_b=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                default_action=FusionAction.KEEP_MORE_POINTS,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#name'),
                    URIRef('http://slipo.eu/def#nameValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#locality'),
                property_b=URIRef('http://slipo.eu/def#locality'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#country'),
                property_b=URIRef('http://slipo.eu/def#country'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#homepage'),
                property_b=URIRef('http://slipo.eu/def#homepage'),
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            )
        ],
        default_dataset_action=DatasetAction.KEEP_LEFT,
        ensembles=Ensembles(
            functional_properties=[],
            non_functional_properties=[]
        )
    )
)

slipo_get_osm_aa_mode = FAGIProfile(
    config=FAGIConfig(
        input_format=SerializationFormat.NT,
        output_format=SerializationFormat.NT,
        left=LeftInputDatasetSettings(id='a'),
        right=RightInputDatasetSettings(id='b'),
        links=LinksFileSettings(
            id='links',
            links_format=LinksFormat.CSV_UNIQUE_LINKS
        ),
        target=FusedOutputDatasetSettings(
            id='target',
            mode=FusionMode.AA,
            fused='fused.nt',
            remaining='remaining.nt',
            ambiguous='review.nt',
            statistics='stats.json'
        )
    ),
    rules=FAGIRulesSpec(
        rules=[
            FAGIValidationRule(
                default_action=ValidationAction.REJECT,
                action_rule_set=[
                    ValidationActionRule(
                        condition=FAGIRuleCondition(
                            And(
                                SimpleFAGIRuleConditionExpression(
                                    GeometriesCloserThan('a0', 'b0', '150')
                                ),
                                SimpleFAGIRuleConditionExpression(
                                    IsSameCustomNormalize('a2', 'b2', '0.8')
                                )
                            )
                        ),
                        action=ValidationAction.ACCEPT
                    ),
                    ValidationActionRule(
                        condition=FAGIRuleCondition(
                            And(
                                SimpleFAGIRuleConditionExpression(
                                    IsSamePhoneNumberCustomNormalize('a3', 'b3')
                                ),
                                SimpleFAGIRuleConditionExpression(
                                    GeometriesCloserThan('a0', 'b0', '150')
                                )
                            )
                        ),
                        action=ValidationAction.ACCEPT
                    ),
                    ValidationActionRule(
                        condition=FAGIRuleCondition(
                            And(
                                SimpleFAGIRuleConditionExpression(
                                    IsSameCustomNormalize('a1', 'b1', '0.85')
                                ),
                                SimpleFAGIRuleConditionExpression(
                                    GeometriesCloserThan('a0', 'b0', '100')
                                )
                            )
                        ),
                        action=ValidationAction.ACCEPT
                    ),
                    ValidationActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(
                                IsSameCustomNormalize('a2', 'b2', '0.9')
                            )
                        ),
                        action=ValidationAction.ACCEPT
                    )
                ],
                external_properties=[
                    ExternalProperty(
                        id='a0',
                        uri=[
                            URIRef(
                                'http://www.opengis.net/ont/geosparql#'
                                'hasGeometry'),
                            URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                        ]
                    ),
                    ExternalProperty(
                        id='b0',
                        uri=[
                            URIRef(
                                'http://www.opengis.net/ont/geosparql#'
                                'hasGeometry'),
                            URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                        ]
                    ),
                    ExternalProperty(
                        id='a1',
                        uri=[
                            URIRef('http://slipo.eu/def#address'),
                            URIRef('http://slipo.eu/def#street')
                        ]
                    ),
                    ExternalProperty(
                        id='b1',
                        uri=[
                            URIRef('http://slipo.eu/def#address'),
                            URIRef('http://slipo.eu/def#street')
                        ]
                    ),
                    ExternalProperty(
                        id='a2',
                        uri=[
                            URIRef('http://slipo.eu/def#name'),
                            URIRef('http://slipo.eu/def#nameValue')
                        ]
                    ),
                    ExternalProperty(
                        id='b2',
                        uri=[
                            URIRef('http://slipo.eu/def#name'),
                            URIRef('http://slipo.eu/def#nameValue')
                        ]
                    ),
                    ExternalProperty(
                        id='a3',
                        uri=[
                            URIRef('http://slipo.eu/def#phone'),
                            URIRef('http://slipo.eu/def#contactValue')
                        ]
                    ),
                    ExternalProperty(
                        id='b3',
                        uri=[
                            URIRef('http://slipo.eu/def#phone'),
                            URIRef('http://slipo.eu/def#contactValue')
                        ]
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                property_b=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                default_action=FusionAction.KEEP_MORE_POINTS,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#source'),
                    URIRef('http://slipo.eu/def#sourceRef')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#source'),
                    URIRef('http://slipo.eu/def#sourceRef')
                ],
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#source'),
                    URIRef('http://slipo.eu/def#poiRef')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#source'),
                    URIRef('http://slipo.eu/def#poiRef')
                ],
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#accuracy'),
                    URIRef('http://slipo.eu/def#accuracyValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#accuracy'),
                    URIRef('http://slipo.eu/def#accuracyValue')
                ],
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#accuracy'),
                    URIRef('http://slipo.eu/def#accuracyType')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#accuracy'),
                    URIRef('http://slipo.eu/def#accuracyType')
                ],
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef(
                    'http://www.w3.org/2003/01/geo/wgs84_pos#lat'
                ),
                property_b=URIRef(
                    'http://www.w3.org/2003/01/geo/wgs84_pos#lat'
                ),
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef(
                    'http://www.w3.org/2003/01/geo/wgs84_pos#long'),
                property_b=URIRef(
                    'http://www.w3.org/2003/01/geo/wgs84_pos#long'),
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#category'),
                property_b=URIRef('http://slipo.eu/def#category'),
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#name'),
                property_b=URIRef('http://slipo.eu/def#name'),
                default_action=FusionAction.KEEP_MOST_COMPLETE_NAME,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a1'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    ),
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ],
                external_properties=[
                    ExternalProperty(
                        id='a1',
                        uri=[
                            URIRef('http://slipo.eu/def#address'),
                            URIRef('http://slipo.eu/def#street')
                        ]
                    ),
                    ExternalProperty(
                        id='b1',
                        uri=[
                            URIRef('http://slipo.eu/def#address'),
                            URIRef('http://slipo.eu/def#street')
                        ]
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#locality')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#locality')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#country')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#country')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactType')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactType')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#homepage'),
                property_b=URIRef('http://slipo.eu/def#homepage'),
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#area'),
                property_b=URIRef('http://slipo.eu/def#area'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            )
        ],
        default_dataset_action=DatasetAction.KEEP_BOTH,
        ensembles=Ensembles(
            functional_properties=[],
            non_functional_properties=[]
        )
    )
)

slipo_get_osm_ab_mode = FAGIProfile(
    config=FAGIConfig(
        input_format=SerializationFormat.NT,
        output_format=SerializationFormat.NT,
        left=LeftInputDatasetSettings(id='a'),
        right=RightInputDatasetSettings(id='b'),
        links=LinksFileSettings(
            id='links',
            links_format=LinksFormat.CSV_UNIQUE_LINKS
        ),
        target=FusedOutputDatasetSettings(
            id='target',
            mode=FusionMode.AB,
            fused='fused.nt',
            remaining='remaining.nt',
            ambiguous='review.nt',
            statistics='stats.json'
        )
    ),
    rules=FAGIRulesSpec(
        rules=[
            FAGIValidationRule(
                default_action=ValidationAction.REJECT,
                action_rule_set=[
                    ValidationActionRule(
                        condition=FAGIRuleCondition(
                            And(
                                SimpleFAGIRuleConditionExpression(
                                    GeometriesCloserThan('a0', 'b0', '150')
                                ),
                                SimpleFAGIRuleConditionExpression(
                                    IsSameCustomNormalize('a2', 'b2', '0.8')
                                )
                            )
                        ),
                        action=ValidationAction.ACCEPT
                    ),
                    ValidationActionRule(
                        condition=FAGIRuleCondition(
                            And(
                                SimpleFAGIRuleConditionExpression(
                                    IsSamePhoneNumberCustomNormalize('a3', 'b3')
                                ),
                                SimpleFAGIRuleConditionExpression(
                                    GeometriesCloserThan('a0', 'b0', '150')
                                )
                            )
                        ),
                        action=ValidationAction.ACCEPT
                    ),
                    ValidationActionRule(
                        condition=FAGIRuleCondition(
                            And(
                                SimpleFAGIRuleConditionExpression(
                                    IsSameCustomNormalize('a1', 'b1', '0.85')
                                ),
                                SimpleFAGIRuleConditionExpression(
                                    GeometriesCloserThan('a0', 'b0', '100')
                                )
                            )
                        ),
                        action=ValidationAction.ACCEPT
                    ),
                    ValidationActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(
                                IsSameCustomNormalize('a2', 'b2', '0.9')
                            )
                        ),
                        action=ValidationAction.ACCEPT
                    )
                ],
                external_properties=[
                    ExternalProperty(
                        id='a0',
                        uri=[
                            URIRef(
                                'http://www.opengis.net/ont/geosparql#'
                                'hasGeometry'),
                            URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                        ]
                    ),
                    ExternalProperty(
                        id='b0',
                        uri=[
                            URIRef(
                                'http://www.opengis.net/ont/geosparql#'
                                'hasGeometry'),
                            URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                        ]
                    ),
                    ExternalProperty(
                        id='a1',
                        uri=[
                            URIRef('http://slipo.eu/def#address'),
                            URIRef('http://slipo.eu/def#street')
                        ]
                    ),
                    ExternalProperty(
                        id='b1',
                        uri=[
                            URIRef('http://slipo.eu/def#address'),
                            URIRef('http://slipo.eu/def#street')
                        ]
                    ),
                    ExternalProperty(
                        id='a2',
                        uri=[
                            URIRef('http://slipo.eu/def#name'),
                            URIRef('http://slipo.eu/def#nameValue')
                        ]
                    ),
                    ExternalProperty(
                        id='b2',
                        uri=[
                            URIRef('http://slipo.eu/def#name'),
                            URIRef('http://slipo.eu/def#nameValue')
                        ]
                    ),
                    ExternalProperty(
                        id='a3',
                        uri=[
                            URIRef('http://slipo.eu/def#phone'),
                            URIRef('http://slipo.eu/def#contactValue')
                        ]
                    ),
                    ExternalProperty(
                        id='b3',
                        uri=[
                            URIRef('http://slipo.eu/def#phone'),
                            URIRef('http://slipo.eu/def#contactValue')
                        ]
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                property_b=[
                    URIRef('http://www.opengis.net/ont/geosparql#hasGeometry'),
                    URIRef('http://www.opengis.net/ont/geosparql#asWKT')
                ],
                default_action=FusionAction.KEEP_MORE_POINTS,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#source'),
                    URIRef('http://slipo.eu/def#sourceRef')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#source'),
                    URIRef('http://slipo.eu/def#sourceRef')
                ],
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#source'),
                    URIRef('http://slipo.eu/def#poiRef')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#source'),
                    URIRef('http://slipo.eu/def#poiRef')
                ],
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#accuracy'),
                    URIRef('http://slipo.eu/def#accuracyValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#accuracy'),
                    URIRef('http://slipo.eu/def#accuracyValue')
                ],
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#accuracy'),
                    URIRef('http://slipo.eu/def#accuracyType')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#accuracy'),
                    URIRef('http://slipo.eu/def#accuracyType')
                ],
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef(
                    'http://www.w3.org/2003/01/geo/wgs84_pos#lat'
                ),
                property_b=URIRef(
                    'http://www.w3.org/2003/01/geo/wgs84_pos#lat'
                ),
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef(
                    'http://www.w3.org/2003/01/geo/wgs84_pos#long'
                ),
                property_b=URIRef(
                    'http://www.w3.org/2003/01/geo/wgs84_pos#long'
                ),
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#category'),
                property_b=URIRef('http://slipo.eu/def#category'),
                default_action=FusionAction.KEEP_LEFT,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#name'),
                property_b=URIRef('http://slipo.eu/def#name'),
                default_action=FusionAction.KEEP_MOST_COMPLETE_NAME,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#street')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#number')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a1'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    ),
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ],
                external_properties=[
                    ExternalProperty(
                        id='a1',
                        uri=[
                            URIRef('http://slipo.eu/def#address'),
                            URIRef('http://slipo.eu/def#street')
                        ]
                    ),
                    ExternalProperty(
                        id='b1',
                        uri=[
                            URIRef('http://slipo.eu/def#address'),
                            URIRef('http://slipo.eu/def#street')
                        ]
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#postcode')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#locality')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#locality')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#country')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#address'),
                    URIRef('http://slipo.eu/def#country')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactType')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#phone'),
                    URIRef('http://slipo.eu/def#contactType')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#fax'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#homepage'),
                property_b=URIRef('http://slipo.eu/def#homepage'),
                default_action=FusionAction.KEEP_RIGHT,
                action_rule_set=[
                    ActionRule(
                        condition=FAGIRuleCondition(
                            SimpleFAGIRuleConditionExpression(Exists('a'))
                        ),
                        action=FusionAction.KEEP_LEFT
                    )
                ]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#email'),
                    URIRef('http://slipo.eu/def#contactValue')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=URIRef('http://slipo.eu/def#area'),
                property_b=URIRef('http://slipo.eu/def#area'),
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            ),
            FAGIRule(
                property_a=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                property_b=[
                    URIRef('http://slipo.eu/def#openingHours'),
                    URIRef('http://slipo.eu/def#concat')
                ],
                default_action=FusionAction.KEEP_LONGEST,
                action_rule_set=[]
            )
        ],
        default_dataset_action=DatasetAction.KEEP_LEFT,
        ensembles=Ensembles(
            functional_properties=[],
            non_functional_properties=[]
        )
    )
)
